name: Check Pull Request Validity

on:
  pull_request:
    branches:
      - main
  
permissions:
  contents: write

jobs:
  check-pull-request-validity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn test

      - name: Make sure the build works
        run: yarn build